'use strict';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d');
const TILE=64,COLS=50,ROWS=40,W=COLS*TILE,H=ROWS*TILE;
const types=[{name:'Turnip',time:12,sheet:'a',row:2},{name:'Corn',time:18,sheet:'b',row:0},{name:'Pumpkin',time:25,sheet:'b',row:1},{name:'Tomato',time:16,sheet:'a',row:3},{name:'Cabbage',time:20,sheet:'a',row:1},{name:'Eggplant',time:22,sheet:'a',row:0},{name:'Radish',time:10,sheet:'b',row:2},{name:'Cauliflower',time:24,sheet:'b',row:3}];
const images={},plots=[],fields=[{x:17,y:15,w:6,h:4,name:'Home fields'},{x:24,y:15,w:5,h:4,name:'East garden'},{x:17,y:23,w:6,h:4,name:'South patch'},{x:8,y:13,w:5,h:4,name:'Meadow garden'},{x:36,y:16,w:5,h:4,name:'River fields'},{x:23,y:7,w:5,h:4,name:'North garden'}];
fields.forEach((f,fi)=>{for(let y=0;y<f.h;y++)for(let x=0;x<f.w;x++)plots.push({x:(f.x+x)*64+32,y:(f.y+y)*64+32,type:-1,age:0,field:fi})});
const player={x:20*64+32,y:20*64+32,dir:3,moving:false},camera={x:0,y:0};let vw=1100,vh=700,zoom=1,selected=0,score=0,remaining=180,elapsed=0,cool=0,crows=[],particles=[],route=[],pending=null,keys=new Set(),running=false,started=false,ended=false,loaded=false,challenge=true,nextCrow=15,last=0,notice=0,walkingTime=0;
function river(c,r){return c>=32+Math.floor(Math.sin(r*.2)*1.5)&&c<=34+Math.floor(Math.sin(r*.2)*1.5)}
function water(c,r){return c<2||r<2||c>=48||r>=38||river(c,r)||((c-9)**2/20+(r-29)**2/12<1)}
function bridge(c,r){return c>=29&&c<=36&&r>=20&&r<=21}
function walkable(c,r){return c>=2&&r>=2&&c<48&&r<38&&(!water(c,r)||bridge(c,r))&&!villageBlocked(c,r)}
function pathTile(c,r){return (r>=20&&r<=21&&c>=5&&c<=44)||(c>=14&&c<=15&&r>=7&&r<=32)||(c>=23&&c<=24&&r>=7&&r<=30)||(r===11&&c>=14&&c<=28)||(r===28&&c>=14&&c<=29)||(r===18&&c>=7&&c<=15)}
function sprite(name,sx,sy,sw,sh,x,y,w,h){const img=images[name];if(img)ctx.drawImage(img,sx,sy,sw,sh,Math.round(x),Math.round(y),w,h)}
function tile(kind,x,y){if(kind==='grass')sprite('terrain',55,58,350,350,x,y,64,64);if(kind==='path')sprite('terrain',535,91,252,265,x,y,64,64);if(kind==='soil')sprite('terrain',935,66,337,337,x,y,64,64);if(kind==='water'){const f=Math.floor(elapsed*2)%4;sprite('terrain',56+f*440,484,337,337,x,y,64,64)}if(kind==='fence')sprite('terrain',1346,35,400,390,x,y,64,64)}
function cropImage(type,stage,x,y,size){const t=types[type],s=313.5;sprite(t.sheet,stage*s,t.row*s,s,s,x-size/2,y-size,size,size)}
function terrain(){const c0=Math.max(0,Math.floor(camera.x/64)),r0=Math.max(0,Math.floor(camera.y/64)),c1=Math.min(COLS,Math.ceil((camera.x+vw/zoom)/64)),r1=Math.min(ROWS,Math.ceil((camera.y+vh/zoom)/64));for(let r=r0;r<r1;r++)for(let c=c0;c<c1;c++){const wet=water(c,r);tile(wet?'water':'grass',c*64,r*64);if(!wet&&((c*31+r*17)%13===0)){ctx.fillStyle='#16471015';ctx.fillRect(c*64,r*64,64,64)}if((!wet&&pathTile(c,r))||bridge(c,r))tile('path',c*64,r*64);if(wet&&!bridge(c,r)){ctx.fillStyle='#bdeda24a';if(walkable(c-1,r))ctx.fillRect(c*64,r*64,4,64);if(walkable(c+1,r))ctx.fillRect(c*64+60,r*64,4,64)}}
for(const f of fields){if(f.x*64>camera.x+vw/zoom||f.x*64+f.w*64<camera.x||f.y*64>camera.y+vh/zoom||f.y*64+f.h*64<camera.y)continue;for(let y=0;y<f.h;y++)for(let x=0;x<f.w;x++)tile('soil',(f.x+x)*64,(f.y+y)*64)}
renderFences();

}
function label(text,x,y){ctx.font='bold 12px monospace';ctx.textAlign='center';const w=ctx.measureText(text).width;ctx.fillStyle='#173b27c9';ctx.fillRect(x-w/2-12,y-17,w+24,25);ctx.fillStyle='#fff3cf';ctx.fillText(text,x,y)}
function crop(p){if(p.type<0)return;const g=Math.min(1,p.age/types[p.type].time),stage=g<.16?0:g<.55?1:2;cropImage(p.type,stage,p.x,p.y+27,stage===0?38:stage===1?50:64);if(g<1){ctx.fillStyle='#283e26';ctx.fillRect(p.x-20,p.y+25,40,4);ctx.fillStyle='#ccdc78';ctx.fillRect(p.x-20,p.y+25,40*g,4)}else{const y=p.y-37+Math.sin(elapsed*4+p.x)*3;ctx.fillStyle='#fff3a3';ctx.fillRect(p.x-1,y-4,3,10);ctx.fillRect(p.x-5,y,11,3)}}
function farmer(){ctx.fillStyle='#17362255';ctx.beginPath();ctx.ellipse(player.x,player.y+3,16,6,0,0,7);ctx.fill();const frame=player.moving&&running?Math.floor(walkingTime*9)%4:1;sprite('player',frame*50,player.dir*46,50,46,player.x-35,player.y-57,70,64)}
function crow(b){const frame=Math.floor(elapsed*9)%4,row=b.eat>0?1:0;sprite('crow',frame*64,row*64,64,64,b.x-32,b.y-37,64,64);if(b.eat>0){ctx.fillStyle='#442e29';ctx.fillRect(b.x-19,b.y-40,38,5);ctx.fillStyle='#ed9165';ctx.fillRect(b.x-19,b.y-40,38*(1-b.eat/6),5)}}
function draw(){ctx.imageSmoothingEnabled=false;ctx.fillStyle='#207ead';ctx.fillRect(0,0,vw,vh);ctx.save();ctx.scale(zoom,zoom);ctx.translate(-Math.round(camera.x),-Math.round(camera.y));terrain();for(const p of plots)if(Math.abs(p.x-camera.x-vw/zoom/2)<vw/zoom/2+70&&Math.abs(p.y-camera.y-vh/zoom/2)<vh/zoom/2+70)crop(p);if(pending){ctx.strokeStyle='#ffe69e';ctx.lineWidth=3;ctx.strokeRect(pending.x-30,pending.y-30,60,60)}renderVillage();crows.forEach(crow);for(const p of particles){ctx.globalAlpha=Math.min(1,p.life);ctx.font='bold 17px monospace';ctx.textAlign='center';ctx.fillStyle=p.color;ctx.fillText(p.text,p.x,p.y)}ctx.globalAlpha=1;ctx.restore();drawMap()}
const map=$('minimap'),mc=map.getContext('2d');function drawMap(){mc.fillStyle='#2289b0';mc.fillRect(0,0,150,120);for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++)if(walkable(c,r)){mc.fillStyle=pathTile(c,r)||bridge(c,r)?'#d3a564':'#6eab40';mc.fillRect(c*3,r*3,3,3)}for(const f of fields){mc.fillStyle='#986031';mc.fillRect(f.x*3,f.y*3,f.w*3,f.h*3)}villageMap();mc.strokeStyle='#fff9cfaa';mc.lineWidth=1;mc.strokeRect(camera.x/W*150,camera.y/H*120,vw/zoom/W*150,vh/zoom/H*120);mc.fillStyle='#ffdf67';mc.fillRect(player.x/W*150-2,player.y/H*120-2,4,4);for(const b of crows){mc.fillStyle='#ff786a';mc.fillRect(b.x/W*150-2,b.y/H*120-2,4,4)}}
function resize(){const b=canvas.getBoundingClientRect();vw=Math.round(b.width);vh=Math.round(b.height);canvas.width=vw;canvas.height=vh;zoom=vw<600?1:1.2;follow(true)}function follow(snap=false){const tx=Math.max(0,Math.min(W-vw/zoom,player.x-vw/zoom/2)),ty=Math.max(0,Math.min(H-vh/zoom,player.y-vh/zoom*.49));camera.x=snap?tx:camera.x+(tx-camera.x)*.12;camera.y=snap?ty:camera.y+(ty-camera.y)*.12}
function toast(text){$('toast').textContent=text;notice=4;$('toast').style.opacity=1}function burst(x,y,text,color='#fff4b7'){particles.push({x,y,text,color,life:1.4})}function beep(){}
function findPath(x,y,origin=player){const start=[Math.floor(origin.x/64),Math.floor(origin.y/64)],end=[Math.floor(x/64),Math.floor(y/64)];if(!walkable(...end))return null;const k=(c,r)=>r*COLS+c,s=k(...start),goal=k(...end),queue=[start],prev=new Map([[s,null]]);for(let i=0;i<queue.length;i++){let [c,r]=queue[i],id=k(c,r);if(id===goal)break;for(let [dc,dr]of [[0,1],[1,0],[-1,0],[0,-1]]){let nc=c+dc,nr=r+dr,n=k(nc,nr);if(walkable(nc,nr)&&!prev.has(n)){prev.set(n,id);queue.push([nc,nr])}}}if(!prev.has(goal))return null;let result=[],id=goal;while(id!==s){result.push({x:(id%COLS)*64+32,y:Math.floor(id/COLS)*64+32});id=prev.get(id)}result.reverse();const center={x:start[0]*64+32,y:start[1]*64+32};if(Math.hypot(origin.x-center.x,origin.y-center.y)>1)result.unshift(center);return result}
function go(x,y,p=null){const found=findPath(x,y);if(found===null){toast('That spot is blocked. Use a gate, path or bridge.');return}route=found;pending=p;if(!route.length&&p)interact(p)}
function interact(p){if(!running)return;if(p.kind){villageInteract(p);return;}if(p.owner){toast(villagers.find(n=>n.id===p.owner).name+' tends these rows. The lower rows are yours to use.');pending=null;return;}if(!sameField(p)){toast('Enter through the gate to reach your crops.');pending=null;return;}if(p.type<0){if(seeds[selected]<=0){toast('No '+types[selected].name.toLowerCase()+' seeds left. Buy more at the market.');pending=null;return;}seeds[selected]--;p.type=selected;p.age=0;beep(350)}else if(p.age>=types[p.type].time){inventory[p.type]++;p.type=-1;p.age=0;score++;burst(p.x,p.y-25,'+1');beep(650);if(challenge&&score>=30)finish(true)}else toast(types[p.type].name+' · '+Math.ceil(types[p.type].time-p.age)+'s until harvest');pending=null;updateUI()}
function shoo(b){if(!running)return;if(cool>0){toast('Whistle ready in '+Math.ceil(cool)+' seconds.');return}const near=crows.filter(b=>Math.hypot(b.x-player.x,b.y-player.y)<560);if(!near.length){toast('No crows nearby. Watch the red marks on your map.');return}near.forEach(b=>burst(b.x,b.y,'Shoo!'));crows=crows.filter(b=>!near.includes(b));cool=WHISTLE_COOLDOWN;beep(800)}
function updateUI(){updateEconomy();const ripe=plots.filter(p=>p.type>=0&&p.age>=types[p.type].time&&!p.owner&&sameField(p)&&Math.hypot(p.x-player.x,p.y-player.y)<320).length;$('score').textContent=score;$('harvest-target').textContent=challenge?' / 30':' picked';$('clock-label').textContent=challenge?'TIME LEFT':'DAYLIGHT';$('clock').textContent=challenge?Math.floor(Math.ceil(remaining)/60)+':'+String(Math.ceil(remaining)%60).padStart(2,'0'):'∞';$('ready').textContent=ripe+' nearby';$('harvest').disabled=!ripe;$('cooldown').textContent=cool>0?'Ready in '+Math.ceil(cool)+'s':'Space · nearby flock';$('shoo').disabled=cool>0;$('progress').style.width=Math.min(100,score/30*100)+'%';$('goaldetail').textContent=challenge?score+' / 30 picked':score+' crops harvested';$('region').textContent=player.x>2200?'River fields':player.x<950?'Wildflower meadow':player.y<850?'North garden':player.y>1500?'South pastures':'Home fields'}
function finish(won){running=false;ended=true;route=[];pending=null;$('modaleyebrow').textContent=won?'HARVEST COMPLETE':'SUNSET AT THE FARM';$('modaltitle').textContent=won?'A basket well earned.':'Another day to grow.';$('modalcopy').textContent='You harvested '+score+' crops. Explore freely to discover all six gardens, or try the challenge again.';$('instructions').hidden=true;$('start').textContent='Return for another day';$('explore').hidden=false;$('close').hidden=true;$('modal').showModal()}
function reset(timed){resetVillage();challenge=timed;score=0;remaining=180;elapsed=0;cool=0;crows=[];particles=[];route=[];pending=null;nextCrow=15;ended=false;started=true;running=true;player.x=20*64+32;player.y=20*64+32;plots.forEach(p=>{p.type=-1;p.age=0;p.tended=false});for(let i=0;i<12;i++){plots[i+12].type=i%8;plots[i+12].age=types[i%8].time*(.25+(i%4)*.2)}follow(true);toast('E to interact · B for basket · visit Mira to sell your harvest');updateUI()}
function start(timed){if(!loaded)return;if(!started||ended||challenge!==timed)reset(timed);else running=true;$('modal').close();$('pause').textContent='Ⅱ'}
function help(){if(ended)return;running=false;keys.clear();$('modaleyebrow').textContent='SUMMER · DAY 01';$('modaltitle').textContent='Welcome to<br>Clover Cove.';$('modaltitle').innerHTML='Welcome to<br>Clover Cove.';$('modalcopy').textContent='Your seeds are ready. The neighbours are already out in the fields. Plant a patch, meet the growers, and bring your harvest to Mira’s stall.';$('instructions').hidden=false;$('start').textContent=started?'Return to farm':'Enter the village';$('explore').hidden=started;$('close').hidden=!started;$('modal').showModal()}
$('start').onclick=()=>start(started&&!ended?challenge:false);$('explore').onclick=()=>start(true);$('close').onclick=()=>start(challenge);$('help').onclick=help;$('modal').addEventListener('cancel',e=>{e.preventDefault();if(started&&!ended)start(challenge)});$('pause').onclick=()=>{if(!started||ended||$('modal').open||$('village-dialog').open)return;running=!running;keys.clear();$('pause').textContent=running?'Ⅱ':'▶';$('pause').setAttribute('aria-label',running?'Pause game':'Resume game');toast(running?'Back to the fields.':'Paused · press P to resume')};
function select(i){selected=i;$('selected-seed').textContent=types[i].name+' · '+types[i].time+'s';document.querySelectorAll('.seed').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-pressed',String(i===j))})}document.querySelectorAll('.seed').forEach(b=>b.onclick=()=>select(+b.dataset.seed));$('harvest').onclick=()=>{if(!running)return;for(const p of plots)if(running&&p.type>=0&&p.age>=types[p.type].time&&!p.owner&&sameField(p)&&Math.hypot(p.x-player.x,p.y-player.y)<320)interact(p)};$('shoo').onclick=()=>shoo();
canvas.addEventListener('pointerdown',e=>{if(!running)return;const b=canvas.getBoundingClientRect(),x=(e.clientX-b.left)/zoom+camera.x,y=(e.clientY-b.top)/zoom+camera.y;const crow=crows.find(b=>Math.hypot(x-b.x,y-b.y)<36);if(crow){shoo(crow);return}const object=villageHit(x,y);if(object){approach(object);return;}const p=plots.find(p=>Math.abs(p.x-x)<32&&Math.abs(p.y-y)<32);go(x,y,p)});
map.addEventListener('pointerdown',e=>{if(!running)return;const b=map.getBoundingClientRect();go((e.clientX-b.left)/b.width*W,(e.clientY-b.top)/b.height*H)});
window.addEventListener('keydown',e=>{if($('modal').open||$('village-dialog').open)return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(/^[1-8]$/.test(k))select(+k-1);if(k===' '&&!e.repeat)shoo();if(k==='h'&&!e.repeat)$('harvest').click();if(k==='p'&&!e.repeat)$('pause').click();if(k==='b'&&!e.repeat)$('basket').click();if(k==='e'&&!e.repeat&&running)$('interact').click()});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)$('pause').click()});
document.querySelectorAll('[data-move]').forEach(b=>{const end=()=>keys.delete(b.dataset.move);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.move)});b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end)});
function move(dt){let dx=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),dy=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));if(dx||dy){route=[];pending=null}else if(route.length){const t=route[0];if(!walkable(Math.floor(t.x/64),Math.floor(t.y/64))){route=[];pending=null;return;}const d=Math.hypot(t.x-player.x,t.y-player.y);if(d<=Math.max(5,210*dt)){player.x=t.x;player.y=t.y;route.shift();if(!route.length&&pending)interact(pending)}else{dx=(t.x-player.x)/d;dy=(t.y-player.y)/d}}const d=Math.hypot(dx,dy);player.moving=d>0;if(d){dx/=d;dy/=d;const nx=player.x+dx*210*dt,ny=player.y+dy*210*dt;if(canStand(nx,player.y))player.x=nx;if(canStand(player.x,ny))player.y=ny;player.dir=Math.abs(dx)>Math.abs(dy)?dx>0?0:1:dy>0?3:2;walkingTime+=dt}}
function tick(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(running){elapsed+=dt;if(challenge)remaining=Math.max(0,remaining-dt);cool=Math.max(0,cool-dt);plots.forEach(p=>{if(p.type>=0)p.age+=dt});move(dt);if(!running){follow();if(loaded)draw();requestAnimationFrame(tick);return;}updateVillagers(dt);if(elapsed>=nextCrow){nextCrow=elapsed+9+Math.random()*5;const targets=plots.filter(p=>p.type>=0&&!crows.some(b=>b.target===p));if(targets.length){const target=targets[Math.floor(Math.random()*targets.length)];crows.push({x:target.x+(Math.random()>.5?360:-360),y:target.y-220,target,eat:0});toast('Crow approaching '+fields[target.field].name.toLowerCase()+'!')}}for(const b of crows){if(b.target.type<0){b.gone=true;continue}const dx=b.target.x-b.x,dy=b.target.y-b.y,d=Math.hypot(dx,dy);if(d>3){const step=Math.min(d,dt*80);b.x+=dx/d*step;b.y+=dy/d*step}else{b.eat+=dt;if(b.eat>=6){b.target.type=-1;b.target.age=0;b.gone=true;burst(b.x,b.y,'Stolen!','#ffc2a6');toast('A crow stole a crop in '+fields[b.target.field].name.toLowerCase()+'.')}}}crows=crows.filter(b=>!b.gone);particles.forEach(p=>{p.life-=dt;p.y-=dt*16});particles=particles.filter(p=>p.life>0);notice-=dt;if(notice<=0)$('toast').style.opacity=0;if(challenge&&remaining<=0&&!ended)finish(false);updateUI()}follow();if(loaded)draw();requestAnimationFrame(tick)}
window.addEventListener('resize',resize);const sources={terrain:'terrain.png',a:'crops-a.png',b:'crops-b.png',player:'player.png',crow:'crow.png',buildings:'buildings.png',signs:'signs.png'};Promise.all(Object.entries(sources).map(([key,file])=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>{images[key]=i;resolve()};i.onerror=()=>reject(Error('Could not load '+file));i.src='assets/'+file}))).then(()=>{loaded=true;resize();$('start').disabled=false;$('explore').disabled=false;$('loading').textContent='Single-player village · progress lasts for this session.';draw()}).catch(e=>{$('loading').textContent=e.message+'. Refresh to retry.'});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_farm_state',description:'Read the farm score, player position and crop state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({score,coins,inventory:[...inventory],storage:[...storage],seeds:[...seeds],running,mode:challenge?'challenge':'explore',player:{x:player.x,y:player.y},world:{columns:COLS,rows:ROWS},crows:crows.length,planted:plots.filter(p=>p.type>=0).length})})).catch(()=>{})}catch{}}
initVillage();bindVillage();select(0);help();updateUI();requestAnimationFrame(tick);
